### ISSUE TITLE
Reestructurar Tutorial MongoDB

### ISSUE THREAD

**Issue by amoya87** [alercebroker/mongo-tutorial#7]
1. 
-    Introduction(Intro)
    -    NoSQL, MongoDB, Database, Collection, Document, keys, JSON/BSON, distribución
-    Conection(C)
    -    Shell, PyMongo

2. 
-    Insertion(I)
-    Simple Selection(F1)
-    Update(U)
-    Delete(D)
3.  
-    Complex Selection(F2)
    -    exact match, elemMatch, array match, geographic math

-    Results Modification
    -    Projection(P)
    -    Sorting(S)
    -    Counting(N)	
-    Indexing(X)
4. 
-    Agregation(A)

**Comment by pcastelln** [comment]
Finalmente creo que prefiero mantener lo de sorting, counting, limit y skip en donde estaban originalmente. Todo eso me parece que igual entra dentro de lo básico y no modifica los documentos resultantes. Además se recarga demasiado la sección de búsquedas avanzadas.
